title: 15098742 Canada Inc.
description: "15098742 Canada Inc. is a Canadian software and technology consulting firm providing hands on full stack, frontend, and platform engineering services for businesses and product teams."
url: "https://haneetsingh.github.io/15098742-canada-inc"
show_title: false
theme: minima
plugins:
  - jekyll-seo-tag
