title: "15098742 Canada Inc. | Software & Consulting Services"
description: "Canadian software and technology consulting corporation providing hands on software engineering and technical consulting services to businesses and product teams in Canada."
url: "https://haneetsingh.github.io/15098742-canada-inc"
show_title: false
theme: minima
plugins:
  - jekyll-seo-tag
